### ISSUE TITLE
fails with 3.23.0-Master

### ISSUE THREAD

**Issue by fgfletcher** [NINAnor/GarminCustomMaps#20]
2021-11-19T15:11:07     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.

2021-11-19T15:11:07     WARNING    Traceback (most recent call last):
              File "/Users/garth/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GarminCustomMap/GarminCustomMap.py", line 347, in run
              mapSettings.setFlags(QgsMapSettings.Antialiasing | QgsMapSettings.UseAdvancedEffects | QgsMapSettings.ForceVectorOutput | QgsMapSettings.DrawLabeling)
             TypeError: QgsMapSettings.setFlags(): argument 1 has unexpected type 'int'

NOTE: Works normally with QGIS 3.20.3

GarminCustomMaps Version 3.3 updated at Fri May 1 17:48:34 2020
QGIS version | 3.23.0-Master | QGIS code revision | ac6bbd662d
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS High Sierra (10.13)
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
VectorBender | 0.2.1
AzimuthMeasurement | 0.2.2
rectanglify | 1.0.3
MagneticDeclination | 2.3.1
GarminCustomMap | 3.3
ViewshedAnalysis | 1.7
TerrainShading | 0.9
MemoryLayerSaver | 4.0.4
parcel_plugin | 3.8
valuetool | 3.0.15
shapetools | 3.4.1
mapswipetool_plugin | 1.2
coordinate_capture | 0.2
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

**Comment by chrismuller** [comment]
See pull request. The function .setFlags expects type QgsMapSettings.Flags not int

**Comment by psychedelicious** [comment]
Thanks @chrismuller. I had the same issue on `3.22.2-Białowieża | QGIS code revision | 1601ec46d0` and this fixed it. 

For others with this issue, I'll note that I had to restart QGIS for the edited script to work.

**Comment by fgfletcher** [comment]
Delighted to hear there is a way to fix the problem!  However, I don't know how to apply the fix.  Any tips?

**Comment by psychedelicious** [comment]
> Delighted to hear there is a way to fix the problem! However, I don't know how to apply the fix. Any tips?

Hi, sure happy to give directions. From your initial report, I see you are on a Mac - here are Mac-specific instructions:

**edit - see the instructions in [this](https://github.com/NINAnor/GarminCustomMaps/issues/20#issuecomment-1015199102) post, which work for any operating system**

If something goes wrong or it still doesn't work, you can revert by reinstalling the plugin from QGIS.

**Comment by fgfletcher** [comment]
WONDERFUL - it works perfectly.
Many many thanks for those very clear instructions.

**Comment by psychedelicious** [comment]
> WONDERFUL - it works perfectly.
> Many many thanks for those very clear instructions.

That’s great to hear, glad you got it working. Cheers

**Comment by andrea-bistacchi** [comment]
Hello, I am getting the same error on a freshly installed QGis 3.22 (the latest version o the standard download page).

It looks like the GarminCustomMaps plugin that goes with 3.22 does not have this bug fixed

What shall I do?

Thanks very much!

**Comment by psychedelicious** [comment]
@andrea-bistacchi 

Hi, here are general instructions that will work for any operating system:

- Right-click and download/save [this file](https://raw.githubusercontent.com/NINAnor/GarminCustomMaps/ca195aa88ffc5746e3e3b8a8891a83db6598f8c2/GarminCustomMap.py) (save it anywhere, Downloads is fine)
- In QGIS, click **Settings** > **User Profiles** > **Open Active Profile Folder**
- In this folder, go into **python** > **plugins** > **GarminCustomMap**
- Copy the downloaded `GarminCustomMap.py` file and paste in this folder, replacing the existing `GarminCustomMap.py`
- Restart QGIS

**Comment by andrea-bistacchi** [comment]
Hello, now it works, but it grabs just the vector layers, not the raster ones.

Thanks!

**Comment by andrea-bistacchi** [comment]
Update: I created pyramids for my rasters. Now GarminCustomMaps captures some of them but places them in the wrong position, basically in one tile only, leaving all the other tiles in white.

**Comment by psychedelicious** [comment]
@andrea-bistacchi Sorry, I don't know what could be wrong - the fix from @chrismuller  works for me with rasters. Hopefully one of the plugin developers can assist. 

Maybe you could try installing an older version of QGIS that works with the plugin without the fix. If I recall correctly, it worked for me on QGIS 3.18, not sure about the versions between that and 3.22.

**Comment by andrea-bistacchi** [comment]
Hello, I removed 3.22 and reinstalled 3.18 and it works. No need to patch the Python file.

Thanks!

**Comment by veroniqueC** [comment]
Hy,

I have the same issue with QGIS 3.22.5. The patch resolved the problem. 
Thanks

**Comment by esan0** [comment]
I think we can close this issue. The plugin no longer fails.
