### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by alhirzel** [NINAnor/GarminCustomMaps#30]
The following [link](https://forums.garmin.com/showthread.php?t=2646) no longer works:

https://github.com/NINAnor/GarminCustomMaps/blob/d9da9b2bcc4ac3a77ccc709835065470cde2b444/GarminCustomMap.py#L333-L334

**Comment by esan0** [comment]
We'll fix that in the next release.

Meanwhile, the details are now available here:
https://support.garmin.com/en-US/?faq=UcO3cFueS12IwCnizrJjeA
