### ISSUE TITLE
Support for QGIS 3.2

### ISSUE THREAD

**Issue by JarrodSharp** [NINAnor/GarminCustomMaps#4]
Hi - I don't seem to be able to get this plugin to work with the new 3.2 version of QGIS - has anyone done any work to get this functionality into the 3.2 version? or can offer any suggestions?

**Comment by ninsbl** [comment]
It is not yet ported to QGIS 3 API. Should not be too much work as only little code depends on QGIS functionalities. However, I unfortunately cannot forsee when I will find the time to do it. Any help is greatly welcome.

**Comment by Jesseov** [comment]
+1 Any temporary work around to get it working.?  I'm good at following instructions, just not finding solutions!

**Comment by ghtmtt** [comment]
fiexed in https://github.com/NINAnor/GarminCustomMaps/pull/6
