### ISSUE TITLE
error exporting for Garmin 64s

### ISSUE THREAD

**Issue by elorigoni** [NINAnor/GarminCustomMaps#8]
when exporting with zoom for device with 500 tiles, I get this error:

2019-02-27T23:04:50     WARNING    Traceback (most recent call last):
              File "/Users/----xx----/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/GarminCustomMap/GarminCustomMap.py", line 493, in run
              iface.messageBar().pushMessage("WARNING", "The number of tiles is likely to exceed Garmins limit of 100 tiles! Not all tiles will be displayed on your GPS unit. Consider reducing your map size (extend or zoom-factor).", level=QgsMessageBar.WARNING, duration=5)
             AttributeError: type object 'QgsMessageBar' has no attribute 'WARNING'

and no file is produced.

elia

**Comment by pcav** [comment]
Don't you think the error message is clear enough?
Perhaps it could be displayed in a popup, so it is more clear to the user.

**Comment by ninsbl** [comment]
Seems like a bug to me.
, level=QgsMessageBar.WARNING should be probably deleted from 
iface.messageBar().pushMessage()... See:
https://qgis.org/api/classQgsMessageBar.html#ae38eabd4166bfc89e2566286b158c939
Also "duration attribute is no longer part of the message itself, but rather of the QgsMessageBarItem...

**Comment by jwidness** [comment]
I'm still getting this problem -- same message and no file produced.  Does the QGIS plugin manager somehow not have the most recent build?

 line 493, in run
              iface.messageBar().pushMessage("WARNING", "The number of tiles is likely to exceed Garmins limit of 100 tiles! Not all tiles will be displayed on your GPS unit. Consider reducing your map size (extend or zoom-factor).", level=QgsMessageBar.WARNING, duration=5)
             AttributeError: type object 'QgsMessageBar' has no attribute 'WARNING'

**Comment by haltoid** [comment]
Hi, I'm pretty new to this.  I'm also using the GPSMAP64 and I wanted 500 tiles.  I got the same error.  Do you know where I can change that setting?

**Comment by jwidness** [comment]
As far as I can tell, there's currently no way to get 500 tiles.  The best I was able to do was lower the zoom factor until it produced fewer than 100 tiles.

**Comment by haltoid** [comment]
Thanks for the quick response and info!

**Comment by patrice-geo** [comment]
It seems like the issue has been fixed with **commit 56c21f1** but the new source has not been uploaded to the QGIS plugin repository.
